name: CI-CD Pipeline

on:
  pull_request:
    branches: [test]
  push:
    branches: [test]

env:
  IMAGE_NAME: laravel-app

# =====================================================
# ðŸ” DETECT TERRAFORM CHANGES (PATH FILTER)
# =====================================================
jobs:
  detect_changes:
    name: Detect Infra Changes
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.filter.outputs.changes }}

    steps:
      - uses: actions/checkout@v4

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            changes:
              - 'terraform/**'

# =====================================================
# ðŸ§ª TEST STAGE
# =====================================================
  test:
    name: Laravel Tests
    runs-on: ubuntu-latest
    needs: detect_changes

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_mysql

      - run: composer install --no-interaction --prefer-dist
      - run: |
          cp .env.example .env
          php artisan key:generate
      - run: php artisan test

# =====================================================
# ðŸŒ TERRAFORM PLAN (ALL ENVS)
# =====================================================
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: [test, detect_changes]
    if: needs.detect_changes.outputs.changes == 'true'

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # ðŸ”¹ ENV â†’ tfvars
      - name: Select Terraform Variables
        run: |
          if [[ "${GITHUB_REF_NAME}" == "development" ]]; then
            echo "TF_VAR_FILE=dev.tfvars" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "staging" ]]; then
            echo "TF_VAR_FILE=staging.tfvars" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "test" ]]; then
             echo "TF_VAR_FILE=dev.tfvars" >> $GITHUB_ENV
          else
            echo "TF_VAR_FILE=prod.tfvars" >> $GITHUB_ENV
          fi

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -var-file=${TF_VAR_FILE} -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/tfplan

# =====================================================
# âœ‹ TERRAFORM APPLY (ONLY MAIN + PRODUCTION)
# =====================================================
  terraform-apply:
    name: Terraform Apply (Production)
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.event_name == 'push' && github.ref_name == 'main'
  
    # environment: production  #  Manual approval enabled

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: terraform

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply tfplan

# =====================================================
# ðŸ— BUILD STAGE (APP)
# =====================================================
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs:
      - test
     # - terraform-apply
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Image
        run: |
          TAG=${GITHUB_SHA::7}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:$TAG .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME}:$TAG
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

# =====================================================
# ðŸš€ DEPLOY STAGE (EKS)
# =====================================================
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Select App Environment
        run: |
          if [[ "${GITHUB_REF_NAME}" == "development" ]]; then
            echo "ENV=dev" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "staging" ]]; then
            echo "ENV=staging" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "test" ]]; then
            echo "ENV=dev" >> $GITHUB_ENV
          else
            echo "ENV=prod" >> $GITHUB_ENV
          fi

      - name: Helm Dry Run
        run: |
          helm template laravel helm/laravel.app \
            -f helm/laravel.app/values-${ENV}.yaml \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/${IMAGE_NAME} \
            --set image.tag=${IMAGE_TAG}
